object Features {
    const val chat = ":features:chat"
    const val myChats = ":features:mychats"
    const val addChat = ":features:add-chat"
    const val notifications = ":features:notifications"
    const val profile = ":features:profile"
    const val editProfile = ":features:edit-profile"
    const val feed = ":features:feed"
    const val imagePosting = ":features:posting"
    const val post = ":features:post"
    const val login = ":features:login"
    const val visitProfile = ":features:visit-profile"
    const val textPosting = ":features:text-post"
    const val search = ":features:search"
}